# Generated by Django 5.2.5 on 2025-09-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
    ]
